### ISSUE TITLE
hosting probem

### ISSUE THREAD

**Issue by Ashish07s** [rammazzoti2000/personal_portfolio#45]
Im creating a my portfolio same as u but free hosting is not done on my project ,
local host is done and npm start has actually run but main thing is firebase or other github freehost web is not hosted my website
so plz help me

**Comment by rammazzoti2000** [comment]
As you noticed from Readme description, the project is hosted on Netlify (free service).
I used Netlify because it automates the building service each time I make new changes.

If you need help we could meet later on today.
But please try this guide before, and let me know how it goes.
https://blog.logrocket.com/3-ways-to-deploy-react-apps-to-netlify/

**Comment by Ashish07s** [comment]
No sir Im not getting correct,
I created a website like yours but I want to host it for free, I did it on
Firebase but there is an error, so plz help sir ,
I need ur help sir can u plz explain step by step solution of this ....
    Please sir

**Comment by Ashish07s** [comment]
plz reply me sir

**Comment by rammazzoti2000** [comment]
Are you still online?
Please join the meeting so we can talk more easily.
meet.google.com/hyf-wrzj-fvf
